name: Check, Test and Build ZPC

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    name: "Build & Test [${{ matrix.os }}]"
    strategy:
      matrix:
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      # Necessary to run before rust-cache
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2

    - name: Build ZPLC
      id: build
      timeout-minutes: 5
      run: cargo build --verbose --features v1

    - name: Test ZPLC
      timeout-minutes: 5
      run: cargo test --verbose --features v1

    - name: Check format
      if: ${{ ! cancelled() }}
      timeout-minutes: 5
      run: cargo fmt --check

    - name: Check warnings
      if: ${{ ! cancelled() }}
      timeout-minutes: 5
      run: cargo build --all-targets --features v1 --config 'build.rustflags = ["-D", "warnings"]'
